### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/chooify#1]
Things to be implemented
- [x] `require` .choo files.
  - [x] Read view property from required object.
  - [x] Read model property from required object.
- [x] Ignore namespace from model.
- [x] Ignore state declaration from component models.
- [ ] Bind the local property to the `this` scope of the component (in model).
- [x] Bind the local property to the ~~global~~ `this` scope in views.
- [ ] Pass local data to components when required.
- ~~Wrap initial state for state initialization~~

**Comment by YerkoPalma** [comment]
Re render a component after every local change. Use [nanoraf](https://github.com/yoshuawuyts/nanoraf) and some choo hook (maybe onAction or similar)
- ref: https://github.com/yoshuawuyts/choo/blob/master/index.js#L89-L97
